homepage:
    resource: "@AppBundle/Resources/config/routing/homepage.yml"
    prefix:   /

rest:
    resource: "@AppBundle/Resources/config/routing/rest.yml"
    prefix:   /

#
#aisel_navigation:
#    resource: "@AiselNavigationBundle/Resources/config/routing.yml"
#    prefix:   /