hello:
    pattern:  /rest/index.{_format}
    defaults: { _controller: AppBundle:Rest:index, _format: html }

register:
    pattern:  /rest/register
    defaults: { _controller: AppBundle:Rest:register, _format: html }
    methods: [POST]

form_in_partial:
    pattern:  /rest/form_in_partial
    defaults: { _controller: AppBundle:Rest:formInPartial }

form_from_twig:
    pattern:  /rest/form_in_twig
    defaults: { _controller: AppBundle:Rest:formInTwig }

form_from_twig_process:
    pattern:  /rest/form_in_twig_process
    defaults: { _controller: AppBundle:Rest:formInTwigProcess }